import {View, Text, ScrollView} from 'react-native';
import React from 'react';
import {ButtonPrimary} from '../../components/ButtonPrimary';
import {ButtonSecondary} from '../../components/ButtonSecondary';
import {ButtonOutline} from '../../components/ButtonOutline';
import {ButtonTransparent} from '../../components/ButtonTransparent';
import {NavBars} from '../../components/bars/NavBars';
import ArrowRight from '../../../assets/vectors/arrow-right.svg';

export const WelcomeScreen = () => {
  return (
    <ScrollView>
      <ButtonPrimary
        label="Block Primary"
        showArrowSign={false}
        showMessageSign={false}
        primaryBlock
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        primaryBlock
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        primaryBlock
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        centered
        primaryBlock
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={false}
        disabled
        primaryBlock
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        primaryBlock
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        primaryBlock
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        primaryBlock
        centered
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        hasArrowSign={false}
        hasMessageSign={false}
        primaryLarge
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        primaryLarge
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        primaryLarge
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        centered
        primaryLarge
      />
      <ButtonPrimary
        label="Block+Primary"
        hasArrowSign={false}
        hasMessageSign={false}
        primaryLarge
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        primaryLarge
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        primaryLarge
        disabled
      />
      <ButtonPrimary
        label="Button Large"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        centered
        primaryLarge
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        hasArrowSign={true}
        hasMessageSign={true}
        primarySmall
      />
      <ButtonPrimary
        label="Block+Primary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        primarySmall
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        primarySmall
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        centered
        primarySmall
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        showMessageSign={false}
        hasArrowSign={false}
        hasMessageSign={false}
        centered
        primarySmall
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        primarySmall
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        primarySmall
        disabled
      />
      <ButtonPrimary
        label="Block+Primary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        primarySmall
        disabled
      />
      <Text>sdfsdsjdbnfksjdbfskdjfnsfnksdfnsnfskjdnfkds,</Text>
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={false}
        secondaryBlock
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        secondaryBlock
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        secondaryBlock
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        centered
        secondaryBlock
      />
      <ButtonPrimary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={false}
        disabled
      />
      <ButtonPrimary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        disabled
      />
      <ButtonPrimary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        disabled
      />
      <ButtonPrimary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        centered
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={false}
        secondaryLarge
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        secondaryLarge
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        secondaryLarge
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        centered
        secondaryLarge
      />
      <ButtonSecondary
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={false}
        secondaryLarge
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        secondaryLarge
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        secondaryLarge
        disabled
      />
      <ButtonSecondary
        label="Button Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        secondaryLarge
        centered
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        hasArrowSign={true}
        hasMessageSign={true}
        secondarySmall
      />
      <ButtonSecondary
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        secondarySmall
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        secondarySmall
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        centered
        secondarySmall
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={false}
        hasArrowSign={false}
        hasMessageSign={false}
        centered
        secondarySmall
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        secondarySmall
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        secondarySmall
        disabled
      />
      <ButtonSecondary
        label="Block+Secondary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        secondarySmall
        disabled
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        outlineBlock
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        outlineBlock
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={true}
        showMessageSign={false}
        outlineBlock
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        centered
        outlineBlock
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        outlineBlock
        disabled
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        outlineBlock
        disabled
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={true}
        showMessageSign={false}
        outlineBlock
        disabled
      />
      <ButtonOutline
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        outlineBlock
        centered
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={false}
        outlineLarge
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        outlineLarge
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        outlineLarge
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        centered
        outlineLarge
      />
      <ButtonOutline
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={false}
        outlineLarge
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        outlineLarge
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasMessageSign={false}
        outlineLarge
        disabled
      />
      <ButtonOutline
        label="Button Secondary"
        showArrowSign={false}
        showMessageSign={true}
        hasArrowSign={false}
        centered
        outlineLarge
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        hasArrowSign={true}
        hasMessageSign={true}
        outlineSmall
      />
      <ButtonOutline
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        outlineSmall
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        outlineSmall
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        centered
        outlineSmall
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        showMessageSign={false}
        hasArrowSign={false}
        hasMessageSign={false}
        centered
        outlineSmall
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        hasArrowSign={false}
        hasMessageSign={true}
        showMessageSign={true}
        outlineSmall
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={true}
        showMessageSign={false}
        hasArrowSign={true}
        hasMessageSign={false}
        outlineSmall
        disabled
      />
      <ButtonOutline
        label="Block+Secondary"
        showArrowSign={false}
        hasArrowSign={false}
        showMessageSign={true}
        hasMessageSign={true}
        outlineSmall
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentBlock
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentBlock
        centered
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentBlock
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentBlock
        centered
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentLarge
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentLarge
        centered
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentLarge
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentLarge
        centered
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentSmall
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentSmall
        centered
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={false}
        transparentSmall
        disabled
      />
      <ButtonTransparent
        label="Block+Outline"
        showArrowSign={false}
        showMessageSign={true}
        transparentSmall
        centered
        disabled
      />
      <Text> Welcome Screen </Text>
    </ScrollView>
  );
};
